"""Recovery event names are persisted by SelfHealingRepository.event."""
RECOVERY_EVENT_TYPES = frozenset({"INCIDENT_CREATED", "INCIDENT_UPDATED", "DIAGNOSIS_COMPLETED", "RECOVERY_ACTION_SELECTED", "RECOVERY_ACTION_EXECUTED", "RECOVERY_ACTION_FAILED", "RECOVERY_VERIFIED", "RECOVERY_ESCALATED", "RECOVERY_LOOP_DETECTED"})
